/* eslint-disable */
import { Center } from '@react-three/drei'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: premudraya (https://sketchfab.com/premudraya)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-assets-c5f2e7eacc0f4e659c4188925fcb84f1
title: Low poly assets
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tree({ ...props }) {
  const group = useRef()
  const RandTree = ({ ...props }) => {
    const { nodes, materials } = useGLTF('./libs/low_poly_assets/scene.gltf')
    const randCord = () => {
      const r = 40,
        θ = 1 * Math.PI * Math.random() - Math.PI / 2
      let x = r * Math.sin(θ)
      let z = r * Math.cos(θ) + Math.random() * 5
      return { x, z }
    }
    const randCords = []
    for (let x = 0; x < 5; x++) randCords.push(randCord())
    return (
      <group>
        <group position={[randCords[0].x, 1.4, randCords[0].z]}>
          <mesh
            scale={0.25}
            geometry={nodes.mesh_0.geometry}
            material={nodes.mesh_0.material}
          />
        </group>
        <group position={[randCords[1].x, 2.2, randCords[1].z]}>
          <mesh
            scale={0.25}
            geometry={nodes.mesh_1.geometry}
            material={nodes.mesh_1.material}
          />
        </group>
        <group position={[randCords[2].x, 2.3, randCords[2].z]}>
          <mesh
            scale={0.25}
            geometry={nodes.mesh_2.geometry}
            material={nodes.mesh_2.material}
          />
        </group>
        <group position={[randCords[3].x, 1.6, randCords[3].z]}>
          <mesh
            scale={0.25}
            geometry={nodes.mesh_3.geometry}
            material={nodes.mesh_3.material}
          />
        </group>
        <group position={[randCords[4], 1, randCords[4]]}>
          <mesh
            scale={0.1}
            geometry={nodes.mesh_10.geometry}
            material={nodes.mesh_10.material}
          />
        </group>
      </group>
    )
  }
  const Trees = () => {
    const trees = []
    for (let i = 0; i < 1; i++) {
      trees.push(<RandTree />)
    }
    return trees
  }
  const { nodes, materials } = useGLTF('./libs/low_poly_assets/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <Trees />
      {/* <group position={[0, 1.4, 31]}>
        <mesh
          scale={0.2}
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
        />
        <axesHelper args={[2]} />
      </group>
      <group position={[8, 2.2, 32]}>
        <mesh
          scale={0.2}
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
        />
        <axesHelper args={[2]} />
      </group>
      <group position={[4, 2.3, 33]}>
        <mesh
          scale={0.2}
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
        />
      </group>
      <group position={[1, 1.6, 34]}>
        <mesh
          scale={0.2}
          geometry={nodes.mesh_3.geometry}
          material={nodes.mesh_3.material}
        />
      </group>
      <group position={[2, 2, 35]} scale={[1, 1, 1]}>
        <mesh
          scale={0.2}
          geometry={nodes.mesh_4.geometry}
          material={nodes.mesh_4.material}
        />
      </group> */}
      {/* <group position={[rand().x, 2.2, rand().z]} scale={[1, 1, 1]}>
        <mesh
          scale={0.2}
          geometry={nodes.mesh_5.geometry}
          material={nodes.mesh_5.material}
        />
      </group> */}
      {/* <group position={[5.19, 0, -16.84]} scale={[0.72, 0.72, 0.72]}>
        <mesh
          geometry={nodes.mesh_6.geometry}
          material={nodes.mesh_6.material}
        />
      </group>
      <group position={[-9.54, 0, -16.83]} scale={[0.96, 0.96, 0.96]}>
        <mesh
          geometry={nodes.mesh_7.geometry}
          material={nodes.mesh_7.material}
        />
      </group> */}
      {/* <group
            position={[-35.86, 0, -13.45]}
  
            scale={[0.83, 0.83, 0.83]}
          >
            <mesh
              geometry={nodes.mesh_8.geometry}
              material={nodes.mesh_8.material}
            />
          </group>
          <group position={[-49.78, 0, -5.59]}>
            <mesh
              geometry={nodes.mesh_9.geometry}
              material={nodes.mesh_9.material}
            />
          </group>
          <group
            position={[-50.63, 0, -13.16]}
            rotation={[-Math.PI, 0.57, -Math.PI]}
            scale={[0.64, 0.64, 0.64]}
          >
            <mesh
              geometry={nodes.mesh_10.geometry}
              material={nodes.mesh_10.material}
            />
          </group>
          <group position={[-64.71, 0, -5.59]} rotation={[0, -0.57, 0]}>
            <mesh
              geometry={nodes.mesh_11.geometry}
              material={nodes.mesh_11.material}
            />
          </group>
          <group
            position={[-65.58, 0, -13.16]}
            rotation={[-Math.PI, 0.57, -Math.PI]}
            scale={[0.64, 0.64, 0.64]}
          >
            <mesh
              geometry={nodes.mesh_12.geometry}
              material={nodes.mesh_12.material}
            />
          </group>
          <group
            position={[27.05, -0, -3.62]}
            rotation={[0, -0.57, 0]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.mesh_13.geometry}
              material={nodes.mesh_13.material}
            />
          </group>
          <group
            position={[32.52, -0, -3.64]}
            rotation={[0, -0.57, 0]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.mesh_14.geometry}
              material={nodes.mesh_14.material}
            />
          </group>
          <group
            position={[37.69, -0, -0.38]}
            rotation={[0, 1.47, 0]}
            scale={0.33}
          >
            <mesh
              geometry={nodes.mesh_15.geometry}
              material={nodes.mesh_15.material}
            />
          </group>
          <group
            position={[39.14, 0, -3.5]}
            rotation={[-1.06, 0.06, 0.28]}
            scale={[0.24, 0.24, 0.24]}
          >
            <mesh
              geometry={nodes.mesh_16.geometry}
              material={nodes.mesh_16.material}
            />
          </group>
          <group
            position={[44.75, 0, -3.5]}
            rotation={[-1.06, 0.06, 0.28]}
            scale={[0.24, 0.24, 0.24]}
          >
            <mesh
              geometry={nodes.mesh_17.geometry}
              material={nodes.mesh_17.material}
            />
          </group>
          <group
            position={[40.29, -0, -0.28]}
            rotation={[0, 1.47, 0]}
            scale={0.33}
          >
            <mesh
              geometry={nodes.mesh_18.geometry}
              material={nodes.mesh_18.material}
            />
          </group>
          <group
            position={[43.47, -0, -0.38]}
            rotation={[0, 1.47, 0]}
            scale={0.33}
          >
            <mesh
              geometry={nodes.mesh_19.geometry}
              material={nodes.mesh_19.material}
            />
          </group>
          <group
            position={[45.87, -0, -0.28]}
            rotation={[0, 1.47, 0]}
            scale={0.33}
          >
            <mesh
              geometry={nodes.mesh_20.geometry}
              material={nodes.mesh_20.material}
            />
          </group>
          <group
            position={[27.05, 0, -8.78]}
            rotation={[0, -0.57, 0]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.mesh_21.geometry}
              material={nodes.mesh_21.material}
            />
          </group>
          <group
            position={[27.05, 0, -12.79]}
            rotation={[0, -0.57, 0]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.mesh_22.geometry}
              material={nodes.mesh_22.material}
            />
          </group>
          <group position={[32.49, -0, -8.4]}>
            <mesh
              geometry={nodes.mesh_23.geometry}
              material={nodes.mesh_23.material}
            />
          </group>
          <group position={[32.49, -0, -12.77]}>
            <mesh
              geometry={nodes.mesh_24.geometry}
              material={nodes.mesh_24.material}
            />
          </group>
          <group position={[32.48, -0, -16.45]}>
            <mesh
              geometry={nodes.mesh_25.geometry}
              material={nodes.mesh_25.material}
            />
          </group>
          <group position={[32.49, -0, -20.25]}>
            <mesh
              geometry={nodes.mesh_26.geometry}
              material={nodes.mesh_26.material}
            />
          </group>
          <group position={[16.06, 0, -4.88]} scale={[2.48, 0.11, 0.11]}>
            <mesh
              geometry={nodes.mesh_27.geometry}
              material={nodes.mesh_27.material}
            />
          </group>
          <group
            position={[39.04, 0, -8.52]}
            rotation={[0, -0.57, 0]}
            scale={[0.49, 0.49, 0.49]}
          >
            <mesh
              geometry={nodes.mesh_28.geometry}
              material={nodes.mesh_28.material}
            />
          </group>
          <group position={[16.06, 0, -11.19]} scale={[2.48, 0.11, 0.11]}>
            <mesh
              geometry={nodes.mesh_29.geometry}
              material={nodes.mesh_29.material}
            />
          </group>
          <group position={[16.14, 0, -14.66]} scale={[0.31, 5.58, 0.31]}>
            <mesh
              geometry={nodes.mesh_30.geometry}
              material={nodes.mesh_30.material}
            />
          </group>
          <group position={[16.03, 0, -21.47]} scale={[0.31, 5.58, 0.31]}>
            <mesh
              geometry={nodes.mesh_31.geometry}
              material={nodes.mesh_31.material}
            />
          </group>
          <group position={[22.42, 0, -15.23]} scale={[0.31, 5.58, 0.31]}>
            <mesh
              geometry={nodes.mesh_32.geometry}
              material={nodes.mesh_32.material}
            />
          </group>
          <group position={[22.18, 0, -20.32]} scale={[0.31, 5.58, 0.31]}>
            <mesh
              geometry={nodes.mesh_33.geometry}
              material={nodes.mesh_33.material}
            />
          </group>
          <group position={[22.42, 0, -10.45]} scale={[0.18, 3.27, 0.18]}>
            <mesh
              geometry={nodes.mesh_34.geometry}
              material={nodes.mesh_34.material}
            />
          </group>
          <group position={[22.42, 0, -4.65]} scale={[0.18, 3.15, 0.18]}>
            <mesh
              geometry={nodes.mesh_35.geometry}
              material={nodes.mesh_35.material}
            />
          </group>
          <group position={[22.44, 0, -24.08]} scale={[0.31, 5.58, 0.31]}>
            <mesh
              geometry={nodes.mesh_36.geometry}
              material={nodes.mesh_36.material}
            />
          </group>
          <group position={[22.07, 0, -28.25]} scale={[0.31, 5.58, 0.31]}>
            <mesh
              geometry={nodes.mesh_37.geometry}
              material={nodes.mesh_37.material}
            />
          </group>
          <group position={[42.44, 0, -25.89]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.mesh_38.geometry}
              material={nodes.mesh_38.material}
            />
          </group>
          <group position={[42.65, 0, -22.81]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.mesh_39.geometry}
              material={nodes.mesh_39.material}
            />
          </group>
          <group position={[30.5, 0, -26.19]} scale={[0.19, 1.1, 0.19]}>
            <mesh
              geometry={nodes.mesh_40.geometry}
              material={nodes.mesh_40.material}
            />
          </group>
          <group position={[35.75, 0, -26.19]} scale={[0.19, 1.1, 0.19]}>
            <mesh
              geometry={nodes.mesh_41.geometry}
              material={nodes.mesh_41.material}
            />
          </group>
          <group position={[30.48, 0, -23.3]} scale={[0.19, 1.1, 0.19]}>
            <mesh
              geometry={nodes.mesh_42.geometry}
              material={nodes.mesh_42.material}
            />
          </group>
          <group position={[35.65, 0, -23.3]} scale={[0.19, 1.1, 0.19]}>
            <mesh
              geometry={nodes.mesh_43.geometry}
              material={nodes.mesh_43.material}
            />
          </group>
          <group position={[25.25, 0, -34.15]} scale={[0.31, 5.58, 0.31]}>
            <mesh
              geometry={nodes.mesh_44.geometry}
              material={nodes.mesh_44.material}
            />
          </group>
          <group position={[25.24, 0, -33.8]} scale={[1.64, 1.64, 0.17]}>
            <mesh
              geometry={nodes.mesh_45.geometry}
              material={nodes.mesh_45.material}
            />
          </group>
          <group position={[20.85, 0, -34.17]} scale={[0.31, 5.58, 0.31]}>
            <mesh
              geometry={nodes.mesh_46.geometry}
              material={nodes.mesh_46.material}
            />
          </group>
          <group position={[20.88, 0, -33.67]} scale={[2.13, 1.99, 1.99]}>
            <mesh
              geometry={nodes.mesh_47.geometry}
              material={nodes.mesh_47.material}
            />
          </group>
          <group position={[15.83, 0, -34.05]} scale={[0.31, 5.58, 0.31]}>
            <mesh
              geometry={nodes.mesh_48.geometry}
              material={nodes.mesh_48.material}
            />
          </group>
          <group
            position={[15.83, 0, -33.6]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.94}
          >
            <mesh
              geometry={nodes.mesh_49.geometry}
              material={nodes.mesh_49.material}
            />
          </group> */}
    </group>
  )
}

useGLTF.preload('/scene.gltf')
