/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function Model({ ...props }) {
//   const group = useRef()
//   const { nodes, materials } = useGLTF('/scene.gltf')
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <mesh
//         geometry={nodes.pine_leaves005_dark_leaves_0.geometry}
//         material={materials.dark_leaves}
//         position={[0.01, 2.51, -0.08]}
//         rotation={[-Math.PI / 2, 0, -1.13]}
//         scale={[0.03, 0.03, 0.06]}
//       />
//       <mesh
//         geometry={nodes.tree_trunk005_dark_tree_trunk_0.geometry}
//         material={materials.dark_tree_trunk}
//         position={[0.02, 0.61, -0.06]}
//         rotation={[-Math.PI / 2, 0, 0]}
//         scale={[0.03, 0.03, 0.03]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/scene.gltf')
