/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: olehlila (https://sketchfab.com/olehlila)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-trees-grass-and-rocks-4e0463f5df36420bb53079f9de35e81f
title: Low Poly Trees Grass and Rocks
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <group position={[23.74, -41.9, -103.88]} rotation={[-Math.PI / 2, 0, 0]} scale={[46.69, 42.23, 100]}>
              <mesh geometry={nodes.BG_Cube_BG2_0.geometry} material={materials.material} />
            </group>
            <group
              position={[-552.36, 0, -451.61]}
              rotation={[-Math.PI / 2, 0, -0.65]}
              scale={[412.77, 412.77, 412.77]}>
              <mesh geometry={nodes.Tree1_Tree1_2001_0.geometry} material={materials['Tree1_2.001']} />
              <mesh geometry={nodes.Tree1_Tree1_0.geometry} material={materials.Tree1} />
            </group>
            <group position={[613.21, 0.22, -396.2]} rotation={[-Math.PI / 2, 0, 1.75]} scale={[60.33, 60.33, 60.33]}>
              <mesh geometry={nodes.Tree2_Tree3_1001_0.geometry} material={materials['Tree3_1.001']} />
              <mesh geometry={nodes.Tree2_Tree3_2001_0.geometry} material={materials['Tree3_2.001']} />
            </group>
            <group position={[207.74, -5.32, 137.94]} rotation={[-1.57, 0, 0]} scale={[179.92, 179.92, 179.92]}>
              <mesh geometry={nodes.Rock1_Rock1_1001_0.geometry} material={nodes.Rock1_Rock1_1001_0.material} />
            </group>
            <group position={[-607, 2.19, 489.44]} rotation={[-1.57, 0, 0]} scale={[63.7, 63.7, 63.7]}>
              <mesh geometry={nodes.Rock3_Rock1_1001_0.geometry} material={nodes.Rock3_Rock1_1001_0.material} />
            </group>
            <group position={[-242.57, -0.01, 486.82]} rotation={[-Math.PI / 2, 0, 1.58]} scale={13.24}>
              <mesh geometry={nodes.Mushroom2_Mushroom4_1_0.geometry} material={materials.Mushroom4_1} />
              <mesh geometry={nodes.Mushroom2_Mushroom4_2_0.geometry} material={materials.Mushroom4_2} />
            </group>
            <group position={[-62.08, 0.19, 488.61]} rotation={[-Math.PI / 2, 0, 1.58]} scale={[4.41, 4.41, 4.41]}>
              <mesh geometry={nodes.Grass1_Grass1_1001_0.geometry} material={nodes.Grass1_Grass1_1001_0.material} />
            </group>
            <group position={[73.26, 0.19, 496.1]} rotation={[-Math.PI / 2, 0, 0.86]} scale={[4.74, 4.74, 4.74]}>
              <mesh geometry={nodes.Grass2_Grass1_1001_0.geometry} material={nodes.Grass2_Grass1_1001_0.material} />
            </group>
            <group position={[-259.31, -0.04, 155.41]} rotation={[-Math.PI / 2, 0, 0]} scale={154.78}>
              <mesh geometry={nodes.Bush1_Bush1_1_0.geometry} material={nodes.Bush1_Bush1_1_0.material} />
            </group>
            <group position={[-681.72, -0.04, 158.32]} rotation={[-Math.PI / 2, 0, 0]} scale={136.1}>
              <mesh geometry={nodes.Bush2_Bush1_1_0.geometry} material={nodes.Bush2_Bush1_1_0.material} />
            </group>
            <group position={[-401.58, -0.07, 486.26]} rotation={[-Math.PI / 2, 0, 0]} scale={145.48}>
              <mesh geometry={nodes.Mushroom1_Mushroom3_2_0.geometry} material={materials.Mushroom3_2} />
              <mesh geometry={nodes.Mushroom1_Mushroom3_1_0.geometry} material={materials.Mushroom3_1} />
            </group>
            <group position={[-766.55, 11.72, 497.11]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.Rock2_Rock1_1_0.geometry} material={nodes.Rock2_Rock1_1_0.material} />
            </group>
            <group position={[709.1, -0.04, 111.93]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.19, 175.19, 175.19]}>
              <mesh geometry={nodes.Rock4_Rock1_1_0.geometry} material={nodes.Rock4_Rock1_1_0.material} />
            </group>
            <group position={[360, 9.17, 497.2]} rotation={[-Math.PI / 2, 0, 1.54]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.Branch_Branch1_1_0.geometry} material={materials.Branch1_1} />
              <mesh geometry={nodes.Branch_Branch1_2_0.geometry} material={materials.Branch1_2} />
            </group>
            <group position={[710.57, -0.04, 474.46]} rotation={[-Math.PI / 2, 0, 0]} scale={[149.29, 149.29, 149.29]}>
              <mesh geometry={nodes.Stump1_Stump1_1_0.geometry} material={materials.Stump1_1} />
              <mesh geometry={nodes.Stump1_Stump1_2_0.geometry} material={materials.Stump1_2} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
